### ISSUE TITLE
Enhancement: [_animation.scss] add reduced motion support for .calcite-animate global CSS class

### ISSUE THREAD

**Issue by caripizza** [Esri/calcite-components#3489]
### Description
Add [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion) CSS media feature for the [`.calcite-animate`](https://github.com/Esri/calcite-components/blob/master/src/assets/styles/_animation.scss#L48) global CSS class. This will ensure animations only apply when the prefers-reduced-motion media feature matches `no-preference` on a system (ie., the class will only animate if a user hasn't enabled "Reduce motion" on their system).

Proposed change (courtesy [@tim-white-esri](https://github.com/Esri/calcite-components/issues/3081#issuecomment-960101416)):
```scss
// because default state is opacity: 0; need to make sure that is explicitly set to 1
@media (prefers-reduced-motion: reduce) {
    .calcite-animate {
        opacity: 1;
        animation: none;
    }
}

@media (prefers-reduced-motion: no-preference) {
    .calcite-animate {
        opacity: 0;
        animation-fill-mode: both;
        animation-duration: var(--calcite-animation-timing);
    }
}

```

### Acceptance Criteria 
The src/assets/styles/_animation.scss global stylesheet includes the new CSS media features (above snippet) for the .calcite-animate class.

### Relevant Info 
See pr #2607 related file changes for helpful information on using the global class.

#### Which Component
n/a (global class)

#### Example Use Case
n/a
