### ISSUE TITLE
Missing leading-side padding in RTL component-notice

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/calcite-components#533]
With LTR notice, #shadow-root div with class "notice-message" has full padding:
![image](https://user-images.githubusercontent.com/2125181/80649343-b0ee0280-8a26-11ea-9552-e64165499ed5.png)
With RTL, div doesn't have padding on right side:
![image](https://user-images.githubusercontent.com/2125181/80649461-eeeb2680-8a26-11ea-997f-9c89d6265db0.png)

Propose modifying calcite-notice.scss to add `only-child` override to RTL just like the LTR has:
```css
:host([dir="rtl"]) {
  .notice-content {
    padding: var(--calcite-notice-spacing-token-small) 0
      var(--calcite-notice-spacing-token-small)
      var(--calcite-notice-spacing-token-small);

    &:first-of-type:not(:only-child) {
      padding-right: var(--calcite-notice-spacing-token-large);
    }
    &:only-child {
      padding: var(--calcite-notice-spacing-token-small);
    }
  }
}
```

This fixes the overall message, but does not fix the final line, which is indented extra:
![image](https://user-images.githubusercontent.com/2125181/80649752-80f32f00-8a27-11ea-8fbd-172237d7ec83.png)
I haven't been able to figure out how to fix this yet.
